config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.i18n import JavaScriptCatalog
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter
from django_js_reverse.views import urls_js

from socialhome.content.views import ContentCreateView
from socialhome.content.viewsets import ContentViewSet, TagViewSet
from socialhome.enums import PolicyDocumentType
from socialhome.viewsets import ImageUploadView
from socialhome.views import (
    HomeView, MarkdownXImageUploadView, ObtainSocialhomeAuthToken, PolicyDocumentView)
from socialhome.users.viewsets import UserViewSet, ProfileViewSet

# API routes
# NOTE! If changing or adding API urls, don't forget to update the JS tests URL config fixtures as follows:
#
#    python manage.py collectstatic_js_reverse
#    mv staticfiles/django_js_reverse/js/reverse.js socialhome/frontend/tests/unit/fixtures/Urls.js
#    rm -rf staticfiles/django_js_reverse
#
router = DefaultRouter()
router.register(r"content", ContentViewSet)
router.register(r"profiles", ProfileViewSet)
router.register(r"tags", TagViewSet)
router.register(r"users", UserViewSet)

schema_view = get_schema_view(
   openapi.Info(
      title=f"{settings.SOCIALHOME_DOMAIN} API",
      default_version='v1',
      terms_of_service=f"{settings.SOCIALHOME_URL}/terms/",
      contact=openapi.Contact(email=settings.SOCIALHOME_CONTACT_EMAIL),
      license=openapi.License(name="AGPLv3"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(r"", include("socialhome.federate.urls", namespace="federate")),

    url(r'^robots\.txt', include('robots.urls')),

    # Streams
    url(r"^streams/", include("socialhome.streams.urls.views", namespace="streams")),

    url(r"^$", HomeView.as_view(), name="home"),

    # User management
    url(r"", include("socialhome.users.urls", namespace="users")),
    url(r"^accounts/", include("allauth.urls")),

    # Markdownx
    # Use our own upload view based on the MarkdownX view
    url(r"^markdownx/upload/$", MarkdownXImageUploadView.as_view(), name="markdownx_upload"),
    url(r"^markdownx/", include("markdownx.urls")),

    # Content
    url(r"^content/", include("socialhome.content.urls", namespace="content")),
    # Fallback for bookmarklet route for cross-project support
    url(r"^bookmarklet/", ContentCreateView.as_view(), name="bookmarklet"),

    # JavaScript translations
    path("jsi18n/", JavaScriptCatalog.as_view(packages=['socialhome'], domain="django") , name="javascript-catalog"),

    # Django URLs in JS
    url(r"^jsreverse/$", urls_js, name="js_reverse"),

    # Admin pages
    url(settings.ADMIN_URL, admin.site.urls),
    url(r"^django-rq/", include("django_rq.urls")),

    # API
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^api/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^api/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    url(r"^api/", include((router.urls, "api"))),
    url(r"^api/image-upload/$", ImageUploadView.as_view(), name="api-image-upload"),
    url(r"^api/streams/", include("socialhome.streams.urls.api", namespace="api-streams")),
    url(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    url(r"^api-token-auth/", ObtainSocialhomeAuthToken.as_view(), name="api-token-auth"),

    # Account
    url(r"^account/", include("dynamic_preferences.urls")),

    # Search
    url(r"^search/", include("socialhome.search.urls", namespace="search")),

    # Policy docs
    path(
        'privacy/',
        PolicyDocumentView.as_view(),
        {'document_type': PolicyDocumentType.PRIVACY_POLICY},
        name="privacy-policy"
    ),
    path(
        'terms/',
        PolicyDocumentView.as_view(),
        {'document_type': PolicyDocumentType.TERMS_OF_SERVICE},
        name="terms-of-service"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SILKY_INSTALLED:
    urlpatterns += [
        url(r'^_silk/', include('silk.urls', namespace='silk')),
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r"^400/$", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")}),
        url(r"^403/$", default_views.permission_denied, kwargs={"exception": Exception("Permission Denied")}),
        url(r"^404/$", default_views.page_not_found, kwargs={"exception": Exception("Page not Found")}),
        url(r"^500/$", default_views.server_error),
    ]
    if settings.DEBUG_TOOLBAR_ENABLED:
        import debug_toolbar
        urlpatterns += [
            url(r"^__debug__/", include(debug_toolbar.urls)),
        ]

if settings.SOCIALHOME_ADDITIONAL_APPS_URLS:
    url_prefix, url_path = settings.SOCIALHOME_ADDITIONAL_APPS_URLS.split(',')
    urlpatterns += [
        url(url_prefix, include(url_path)),
    ]

socialhome/users/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'users'

urlpatterns = [
    url(
        regex=r"^u/(?P<username>[\w.@+-]+)/all/$",
        view=views.UserAllContentView.as_view(),
        name="all-content"
    ),
    url(
        regex=r"^u/(?P<username>[\w.@+-]+)/",
        # CSRF exempt needed for POST to work for ActivityPub object inboxes
        view=csrf_exempt(views.UserDetailView.as_view()),
        name="detail"
    ),
    url(
        regex=r"^u/~update-picture/$",
        view=views.UserPictureUpdateView.as_view(),
        name="picture-update"
    ),
    url(
        regex=r"^u/~api-token/$",
        view=views.UserAPITokenView.as_view(),
        name="api-token",
    ),
    url(
        regex=r"^p/~organize/$",
        view=views.OrganizeContentProfileDetailView.as_view(),
        name="profile-organize"
    ),
    url(
        regex=r"^p/~update/$",
        view=views.ProfileUpdateView.as_view(),
        name="profile-update"
    ),
    url(
        regex=r"^p/~following/$",
        view=views.ContactsFollowingView.as_view(),
        name="contacts-following"
    ),
    url(
        regex=r"^p/~followers/$",
        view=views.ContactsFollowersView.as_view(),
        name="contacts-followers"
    ),
    url(
        regex=r"^p/(?P<uuid>[^/]+)/all/$",
        view=views.ProfileAllContentView.as_view(),
        name="profile-all-content"
    ),
    url(
        regex=r"^p/(?P<uuid>[^/]+)/",
        view=views.ProfileDetailView.as_view(),
        name="profile-detail"
    ),
    path('delete-account/', views.DeleteAccountView.as_view(), name="delete-account"),
]

socialhome/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialAccountSignupForm
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from socialhome.content.utils import safe_text
from socialhome.users.models import Profile, User


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["name", "visibility"]

    def clean_name(self):
        return safe_text(self.cleaned_data["name"])


class UserPictureForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["picture"]


class UserSignupFormMixin(forms.Form):
    account_request_reason = forms.CharField(
        label=_("Account request reason"),
        max_length=255,
        required=True,
        widget=forms.Textarea(),
        help_text=_("This instance requires admin approval for new accounts. Tell us why you would want to have an "
                    "account? Be descriptive with a few sentences to improve the chance of admins approving your "
                    "request."),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not settings.ACCOUNT_SIGNUP_REQUIRE_ADMIN_APPROVAL:
            del self.fields['account_request_reason']

    def save(self, request):
        # noinspection PyUnresolvedReferences
        user = super().save(request)
        if settings.ACCOUNT_SIGNUP_REQUIRE_ADMIN_APPROVAL:
            # noinspection PyUnresolvedReferences
            account_request_reason = self.cleaned_data.get("account_request_reason")
            user.account_request_reason = account_request_reason
            user.save(update_fields=["account_request_reason"])
        return user


class UserSignupForm(UserSignupFormMixin, SignupForm):
    pass


class UserSocialAccountSignupForm(UserSignupFormMixin, SocialAccountSignupForm):
    pass

socialhome/users/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, ListView, UpdateView, TemplateView, DeleteView
from federation.entities.activitypub.django.views import activitypub_object_view
from rest_framework.authtoken.models import Token

from socialhome.content.models import Content
from socialhome.streams.streams import ProfilePinnedStream, ProfileAllStream
from socialhome.streams.views import BaseStreamView
from socialhome.users.forms import ProfileForm, UserPictureForm
from socialhome.users.models import User, Profile
from socialhome.users.serializers import ProfileSerializer
from socialhome.utils import get_full_url

logger = logging.getLogger("socialhome")


class DeleteAccountView(DeleteView):
    model = User

    def get_object(self, queryset=None):
        return User.objects.get(id=self.request.user.id)

    def get_success_url(self):
        return reverse("home")


@method_decorator(activitypub_object_view, name='dispatch')
class UserDetailView(DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get(self, request, *args, **kwargs):
        """Render ProfileDetailView for this user."""
        profile = get_object_or_404(Profile, user__username=kwargs.get("username"))
        return ProfileDetailView.as_view()(request, uuid=profile.uuid)


class UserAllContentView(UserDetailView):
    def get(self, request, *args, **kwargs):
        """Render ProfileDetailView for this user."""
        profile = get_object_or_404(Profile, user__username=kwargs.get("username"))
        return ProfileAllContentView.as_view()(request, uuid=profile.uuid)


class ProfileViewMixin(AccessMixin, BaseStreamView, DetailView):
    data = None
    model = Profile
    object = None
    profile_stream_type = None  # TODO: refactor to use stream type value directly
    slug_field = "uuid"
    slug_url_kwarg = "uuid"
    template_name = "streams/base.html"

    def dispatch(self, request, *args, **kwargs):
        """Handle profile visibility checks.

        Redirect to login if not allowed to see profile.
        """
        try:
            self.set_object_and_data()
        except (ValidationError, ValueError) as ex:
            logger.debug("ProfileViewMixin.dispatch - failed at set_object_and_data: %s", ex)
        if self.data:
            return super().dispatch(request, *args, **kwargs)
        if request.user.is_authenticated:
            self.raise_exception = True
        return self.handle_no_permission()

    def get_json_context(self):
        json_context = super().get_json_context()
        json_context["profile"] = self.data
        return json_context

    def get_page_meta(self):
        meta = super().get_page_meta()
        name = self.object.name if self.object.name else self.object.fid
        meta.update({
            "title": name,
            "description": _("Profile of %s." % name),
        })
        return meta

    def set_object_and_data(self):
        if not self.object:
            self.object = self.get_object()
        if not self.data and self.object.visible_to_user(self.request.user):
            self.data = ProfileSerializer(self.object, context={'request': self.request}).data
            self.data["stream_type"] = self.profile_stream_type

    @property
    def stream_name_extra(self):
        return str(self.object.id)


class ProfileDetailView(ProfileViewMixin):
    profile_stream_type = "pinned"
    stream_class = ProfilePinnedStream

    def dispatch(self, request, *args, **kwargs):
        """Ensure we have pinned content. If not, render all content instead."""
        try:
            self.set_object_and_data()
        except (ValidationError, ValueError) as ex:
            logger.debug("ProfileDetailView.dispatch - failed at set_object_and_data: %s", ex)
        if self.data and not self.data["has_pinned_content"]:
            return ProfileAllContentView.as_view()(request, uuid=self.kwargs.get("uuid"))
        return super().dispatch(request, *args, **kwargs)

    def get_page_meta(self):
        meta = super().get_page_meta()
        meta.update({
            "url": get_full_url(reverse("users:profile-detail", kwargs={"uuid": self.object.uuid})),
        })
        return meta


class ProfileAllContentView(ProfileViewMixin):
    profile_stream_type = "all_content"
    stream_class = ProfileAllStream

    def get_page_meta(self):
        meta = super().get_page_meta()
        meta.update({
            "url": get_full_url(reverse("users:profile-all-content", kwargs={"uuid": self.object.uuid})),
        })
        return meta


class OrganizeContentProfileDetailView(LoginRequiredMixin, ListView):
    model = Content
    template_name = "users/profile_detail_organize.html"

    def get_queryset(self):
        profile = get_object_or_404(Profile, user=self.request.user)
        return Content.objects.profile_pinned(profile, self.request.user).order_by("order")

    def post(self, request, *args, **kwargs):
        """Save sort order."""
        self._save_sort_order(request.POST.get("sort_order").split(","))
        return redirect(self.get_success_url())

    def _save_sort_order(self, card_ids):
        """Update Content `order` values according to sort order."""
        qs_ids = self.get_queryset().values_list("id", flat=True)
        for i in range(0, len(card_ids)):
            # Only allow updating cards that are in our qs
            card_id = int(card_ids[i])
            if card_id in qs_ids:
                Content.objects.filter(id=card_id).update(order=i)

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    form_class = ProfileForm
    model = Profile

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self, queryset=None):
        return Profile.objects.get(id=self.request.user.profile.id)


class UserPictureUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserPictureForm
    model = User
    template_name = "users/userpicture_form.html"

    def get_success_url(self):
        return reverse("users:picture-update")

    def get_object(self, queryset=None):
        return User.objects.get(id=self.request.user.id)


class UserAPITokenView(LoginRequiredMixin, TemplateView):
    template_name = "users/user_api_token.html"

    def get_object(self, queryset=None):
        return User.objects.get(id=self.request.user.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["token"], _created = Token.objects.get_or_create(user=self.request.user)
        return context

    def get_success_url(self):
        return reverse("users:api-token")

    def post(self, request, *args, **kwargs):
        if request.POST.get("regenerate") == "regenerate":
            self.get_object().auth_token.delete()
        return redirect(self.get_success_url())


class BaseContactsView(LoginRequiredMixin, DetailView):
    template_name = "users/contacts.html"
    template_title = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = self.template_title
        context["json_context"] = self.get_json_context()

        return context

    def get_json_context(self):
        return {
            "currentBrowsingProfileId": getattr(getattr(self.request.user, "profile", None), "id", None),
            "isUserAuthenticated": bool(self.request.user.is_authenticated),
        }


class ContactsFollowingView(BaseContactsView):
    model = Profile
    template_title = _("Contacts - following")

    def get_object(self, queryset=None):
        return self.request.user.profile


class ContactsFollowersView(BaseContactsView):
    model = Profile
    template_title = _("Contacts - followers")

    def get_object(self, queryset=None):
        return self.request.user.profile

socialhome/users/templates/users/_actions_column.html
{% load i18n %}

<div>
    <button class="follower-button btn btn-outline-dark {% if not record.id in request.user.profile.following_ids %}hidden{% endif %}" data-action="unfollow" data-profileid="{{ request.user.profile.uuid }}" data-target="{{ record.uuid }}" title="{% trans "Unfollow" %}" aria-label="{% trans "Unfollow" %}"><i class="fa fa-minus"></i></button>
    <button class="follower-button btn btn-outline-dark {% if record.id in request.user.profile.following_ids %}hidden{% endif %}" data-action="follow" data-profileid="{{ request.user.profile.uuid }}" data-target="{{ record.uuid }}" title="{% trans "Follow" %}" aria-label="{% trans "Follow" %}"><i class="fa fa-plus"></i></button>
</div>

socialhome/users/templates/users/_picture_column.html
<div>
    <a href="{% url "users:profile-detail" uuid=record.uuid %}">
        <img class="profile-picture" src="{{ record.safer_image_url_small }}">
    </a>
</div>

socialhome/users/templates/users/admin_approval_required.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{% trans "Admin approval required" %}{% endblock %}

{% block content %}
    <h1>{% trans "Admin approval required" %}</h1>
    <p>
        {% trans "An admin will need to check your account request. An email will be sent to you if your account is approved." %}
    </p>
{% endblock %}

socialhome/users/templates/users/contacts.html
{% extends "base.html" %}
{% load i18n %}
{% load json_context %}
{% load js_reverse %}
{% load static %}

{% block title %}{% trans page_title %}{% endblock %}

{% block content %}
    <div id="app">
        <vue-snotify></vue-snotify>
        <router-view/>
    </div>
{% endblock %}


{% block javascript %}
    {% json_context %}
    {{ block.super }}
    <script type="text/javascript" charset="utf-8">{% js_reverse_inline %}</script>
    <script src="{% static 'dist/vue/js/app.js' %}"></script>
{% endblock %}

{% block css %}
    {{ block.super }}
{% endblock %}

socialhome/users/templates/users/profile_detail_organize.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}{% if object.name %}{{ object.name }}{% else %}{{ object.fid }}{% endif %} - {% trans "Organize content" %}{% endblock %}

{% block containertype %}container{% endblock %}

{% block content %}
    <h1>{% trans "Organize content" %}</h1>
    <form method="post" action="{% url 'users:profile-organize' %}" id="organize-content-form">{% csrf_token %}
        <input type="hidden" name="sort_order" value="">
        <div class="row">
            <div class="col-sm-12 organize-content">
                {% for content in content_list %}
                    <div class="row" data-id="{{ content.id }}">
                        <div class="col-sm-12">
                            <div class="card card-block">
                                <div class="row">
                                    <div class="col-sm-2">
                                        <i class="fa fa-5x fa-arrows-alt"></i>
                                    </div>
                                    <div class="col-sm-10 organize-content--content">
                                        {{ content.rendered|safe }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">{% trans "Save order" %}</button>
    </form>
{% endblock content %}

socialhome/users/templates/users/profile_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{% if object.name %}{{ object.name }}{% else %}{{ object.fid }}{% endif %}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:profile-update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}

socialhome/users/templates/users/user_api_token.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "API token" %}{% endblock %}

{% block content %}
    <h1>{% trans "API token" %}</h1>
    <p>
        {% trans "Copy the token to a client or tool which you want to use for interacting with your Socialhome account." %}
    </p>
    <p><strong>
        {% trans "Important! Do not give anyone access to the token or they will be able to use your account through client apps! If you lose your token or need a new one, click 'Regenerate'." %}
    </strong></p>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-10 w-100">
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="{{ token.key }}" value="{{ token.key }}" readonly onclick="this.select()">
                </div>
            </div>
            <div class="col-2 w-100">
                <div class="form-group">
                    <input type="hidden" value="regenerate" name="regenerate" />
                    <button class="form-control btn btn-danger" type="submit">{% trans "Regenerate" %}</button>
                </div>
            </div>
        </div>
        <div>
            <a href="{% url "users:detail" username=request.user.username %}" class="btn btn-outline-dark">{% trans "Return to profile" %}</a>
        </div>
    </form>
{% endblock %}

socialhome/users/templates/users/user_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Delete account 😯" %}{% endblock %}

{% block content %}
    <h1>{% trans "Delete account 😯" %}</h1>
    <p>{% trans "Are you completely sure? This cannot be undone..." %}</p>
    <p><small>
        {% blocktrans %}
            Hey! Please note that if you <i>do</i> go ahead with this, might we say, drastic action, we will of course
            delete any content you have created on <i>this server</i>. Additionally, we will try to delete the content
            that <i>this server</i> has sent to <i>other servers</i> as requested by <i>you</i>. These servers are owned
            by other people (decentralization <3). If these other servers choose to ignore the delete request or they
            happen to have technical difficulties in deleting the content as requested by us, please contact the
            administrators of the other servers. Thanks <3
        {% endblocktrans %}
    </small></p>
    <form action="" method="post">{% csrf_token %}
        {{ form }}
        <a href="{% url "users:detail" username=request.user.username %}" class="btn btn-primary">{% trans "Nah, take me back!" %}</a>
        <input type="submit" class="btn btn-danger" value="{% trans "I'm leaving, bye" %}" />
    </form>
{% endblock %}

socialhome/users/templates/users/userpicture_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Change profile picture" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change profile picture" %}</h1>
    <h4 class="pt-2">{% trans "Uploading a new picture" %}</h4>
    <p>{% trans "Click the file browse button and choose an image file from your computer. Click 'Save'." %}</p>
    <h4>{% trans "Cropping an existing picture" %}</h4>
    <p>{% trans "Profile pictures are square shaped. If your picture is not square shaped, you can choose a 'point of interest' by clicking the full image preview on the right. Click on the center point you would like your profile picture be around, then click 'Save'." %}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <img src="{{ user.picture.crop.300x300 }}">
                </div>
            </div>
            <div class="col-6">
                <div class="form-group">
                    {{ form.picture }}
                </div>
            </div>
        </div>
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            <a href="{% url "users:detail" username=request.user.username %}" class="btn btn-outline-dark">{% trans "Return to profile" %}</a>
          </div>
        </div>
    </form>
{% endblock %}

{% block css %}
    {{ form.media.css }}
    {{ block.super }}
{% endblock %}

{% block javascript %}
    {{ block.super }}
    {{ form.media.js }}
{% endblock %}