config/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.i18n import JavaScriptCatalog
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter
from django_js_reverse.views import urls_js

from socialhome.content.views import ContentCreateView
from socialhome.content.viewsets import ContentViewSet, TagViewSet
from socialhome.enums import PolicyDocumentType
from socialhome.viewsets import ImageUploadView
from socialhome.views import (
    HomeView, MarkdownXImageUploadView, ObtainSocialhomeAuthToken, PolicyDocumentView)
from socialhome.users.viewsets import UserViewSet, ProfileViewSet

# API routes
# NOTE! If changing or adding API urls, don't forget to update the JS tests URL config fixtures as follows:
#
#    python manage.py collectstatic_js_reverse
#    mv staticfiles/django_js_reverse/js/reverse.js socialhome/frontend/tests/unit/fixtures/Urls.js
#    rm -rf staticfiles/django_js_reverse
#
router = DefaultRouter()
router.register(r"content", ContentViewSet)
router.register(r"profiles", ProfileViewSet)
router.register(r"tags", TagViewSet)
router.register(r"users", UserViewSet)

schema_view = get_schema_view(
   openapi.Info(
      title=f"{settings.SOCIALHOME_DOMAIN} API",
      default_version='v1',
      terms_of_service=f"{settings.SOCIALHOME_URL}/terms/",
      contact=openapi.Contact(email=settings.SOCIALHOME_CONTACT_EMAIL),
      license=openapi.License(name="AGPLv3"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(r"", include("socialhome.federate.urls", namespace="federate")),

    url(r'^robots\.txt', include('robots.urls')),

    # Streams
    url(r"^streams/", include("socialhome.streams.urls.views", namespace="streams")),

    url(r"^$", HomeView.as_view(), name="home"),

    # User management
    url(r"", include("socialhome.users.urls", namespace="users")),
    url(r"^accounts/", include("allauth.urls")),

    # Markdownx
    # Use our own upload view based on the MarkdownX view
    url(r"^markdownx/upload/$", MarkdownXImageUploadView.as_view(), name="markdownx_upload"),
    url(r"^markdownx/", include("markdownx.urls")),

    # Content
    url(r"^content/", include("socialhome.content.urls", namespace="content")),
    # Fallback for bookmarklet route for cross-project support
    url(r"^bookmarklet/", ContentCreateView.as_view(), name="bookmarklet"),

    # JavaScript translations
    path("jsi18n/", JavaScriptCatalog.as_view(packages=['socialhome'], domain="django") , name="javascript-catalog"),

    # Django URLs in JS
    url(r"^jsreverse/$", urls_js, name="js_reverse"),

    # Admin pages
    url(settings.ADMIN_URL, admin.site.urls),
    url(r"^django-rq/", include("django_rq.urls")),

    # API
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^api/swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^api/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    url(r"^api/", include((router.urls, "api"))),
    url(r"^api/image-upload/$", ImageUploadView.as_view(), name="api-image-upload"),
    url(r"^api/streams/", include("socialhome.streams.urls.api", namespace="api-streams")),
    url(r"^api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    url(r"^api-token-auth/", ObtainSocialhomeAuthToken.as_view(), name="api-token-auth"),

    # Account
    url(r"^account/", include("dynamic_preferences.urls")),

    # Search
    url(r"^search/", include("socialhome.search.urls", namespace="search")),

    # Policy docs
    path(
        'privacy/',
        PolicyDocumentView.as_view(),
        {'document_type': PolicyDocumentType.PRIVACY_POLICY},
        name="privacy-policy"
    ),
    path(
        'terms/',
        PolicyDocumentView.as_view(),
        {'document_type': PolicyDocumentType.TERMS_OF_SERVICE},
        name="terms-of-service"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SILKY_INSTALLED:
    urlpatterns += [
        url(r'^_silk/', include('silk.urls', namespace='silk')),
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r"^400/$", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")}),
        url(r"^403/$", default_views.permission_denied, kwargs={"exception": Exception("Permission Denied")}),
        url(r"^404/$", default_views.page_not_found, kwargs={"exception": Exception("Page not Found")}),
        url(r"^500/$", default_views.server_error),
    ]
    if settings.DEBUG_TOOLBAR_ENABLED:
        import debug_toolbar
        urlpatterns += [
            url(r"^__debug__/", include(debug_toolbar.urls)),
        ]

if settings.SOCIALHOME_ADDITIONAL_APPS_URLS:
    url_prefix, url_path = settings.SOCIALHOME_ADDITIONAL_APPS_URLS.split(',')
    urlpatterns += [
        url(url_prefix, include(url_path)),
    ]

socialhome/content/urls.py
from django.conf.urls import url

from socialhome.content import views

app_name = 'content'

urlpatterns = [
    url(r"^bookmarklet/$", views.ContentCreateView.as_view(), name="bookmarklet"),
    url(r"^create/$", views.ContentCreateView.as_view(), name="create"),
    url(r"^(?P<pk>[0-9]+)/~edit/$", views.ContentUpdateView.as_view(), name="update"),
    url(r"^(?P<pk>[0-9]+)/~delete/$", views.ContentDeleteView.as_view(), name="delete"),
    url(r"^(?P<pk>[0-9]+)/~reply/$", views.ContentReplyView.as_view(), name="reply"),

    # Content detail works with three different versions
    # /content/123/  # pk
    # /content/123/slug/  # pk + slug
    # /content/abcd-edfg-ffff-aaaa/  # uuid
    url(r"^(?P<pk>[0-9]+)/$", views.ContentView.as_view(), name="view"),
    url(r"^(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$", views.ContentView.as_view(), name="view-by-slug"),
    url(r"^(?P<uuid>[^/]+)/$", views.ContentView.as_view(), name="view-by-uuid"),
]

socialhome/search/urls.py
from django.conf.urls import url

from socialhome.search.views import GlobalSearchView

app_name = 'search'

urlpatterns = [
    url(r"", GlobalSearchView.as_view(), name="global"),
]

socialhome/users/urls.py
from django.conf.urls import url
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'users'

urlpatterns = [
    url(
        regex=r"^u/(?P<username>[\w.@+-]+)/all/$",
        view=views.UserAllContentView.as_view(),
        name="all-content"
    ),
    url(
        regex=r"^u/(?P<username>[\w.@+-]+)/",
        # CSRF exempt needed for POST to work for ActivityPub object inboxes
        view=csrf_exempt(views.UserDetailView.as_view()),
        name="detail"
    ),
    url(
        regex=r"^u/~update-picture/$",
        view=views.UserPictureUpdateView.as_view(),
        name="picture-update"
    ),
    url(
        regex=r"^u/~api-token/$",
        view=views.UserAPITokenView.as_view(),
        name="api-token",
    ),
    url(
        regex=r"^p/~organize/$",
        view=views.OrganizeContentProfileDetailView.as_view(),
        name="profile-organize"
    ),
    url(
        regex=r"^p/~update/$",
        view=views.ProfileUpdateView.as_view(),
        name="profile-update"
    ),
    url(
        regex=r"^p/~following/$",
        view=views.ContactsFollowingView.as_view(),
        name="contacts-following"
    ),
    url(
        regex=r"^p/~followers/$",
        view=views.ContactsFollowersView.as_view(),
        name="contacts-followers"
    ),
    url(
        regex=r"^p/(?P<uuid>[^/]+)/all/$",
        view=views.ProfileAllContentView.as_view(),
        name="profile-all-content"
    ),
    url(
        regex=r"^p/(?P<uuid>[^/]+)/",
        view=views.ProfileDetailView.as_view(),
        name="profile-detail"
    ),
    path('delete-account/', views.DeleteAccountView.as_view(), name="delete-account"),
]

socialhome/activities/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from enumfields import EnumField
from federation.entities.activitypub.enums import ActivityType
from model_utils.fields import AutoCreatedField


class Activity(models.Model):
    """
    Model for Activities done by a profile.
    """
    content_object = GenericForeignKey('content_type', 'object_id')
    content_type = models.ForeignKey(ContentType, on_delete=models.PROTECT)
    created = AutoCreatedField()
    fid = models.URLField(editable=False, max_length=255, unique=True)
    object_id = models.PositiveIntegerField()
    profile = models.ForeignKey("users.Profile", on_delete=models.CASCADE)
    type = EnumField(ActivityType)

socialhome/forms.py
from markdownx.forms import ImageForm

from socialhome.models import ImageUpload


class MarkdownXImageForm(ImageForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super().__init__(*args, **kwargs)

    def _save(self, *args, **kwargs):
        url = super()._save(*args, **kwargs)
        ImageUpload.objects.create(image=url.replace("/media/", ""), user=self.user)
        return url

socialhome/content/views.py
import logging

from braces.views import UserPassesTestMixin, LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.http.response import Http404
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.templatetags.static import static
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.views.generic.base import TemplateView
from django.views.generic.detail import SingleObjectMixin
from federation.entities.activitypub.django.views import activitypub_object_view

from socialhome.content.enums import ContentType
from socialhome.content.models import Content
from socialhome.content.serializers import ContentSerializer
from socialhome.streams.enums import StreamType
from socialhome.utils import get_full_url

logger = logging.getLogger("socialhome")


class ContentVisibleForUserMixin(UserPassesTestMixin):
    def test_func(self, user):
        """Ensure user owns content."""
        object = self.get_object()
        return (
            bool(object) and object.visible_for_user(user)
        )


class UserOwnsContentMixin(UserPassesTestMixin):
    raise_exception = Http404

    def test_func(self, user):
        """Ensure user owns content."""
        object = self.get_object()
        return (
            bool(object) and hasattr(user, "profile") and object.author == user.profile
        )


class ContentCreateView(LoginRequiredMixin, TemplateView):
    model = Content
    template_name = "content/vue.html"
    is_reply = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["bookmarklet"] = render_to_string("content/bookmarklet.min.js", {}, request=self.request)
        context["is_reply"] = self.is_reply
        context["json_context"] = self.get_json_context()
        return context

    def get_json_context(self):
        return {
            "currentBrowsingProfileId": getattr(getattr(self.request.user, "profile", None), "id", None),
            "isUserAuthenticated": bool(self.request.user.is_authenticated),
        }

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)


class ContentReplyView(ContentVisibleForUserMixin, ContentCreateView, SingleObjectMixin):
    is_reply = True

    def dispatch(self, request, *args, **kwargs):
        content_id = kwargs.get("pk")
        self.object = self.get_object()
        self.parent = get_object_or_404(Content, id=content_id)
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return self.parent.get_absolute_url()

    def get_json_context(self):
        val = super().get_json_context()
        mentions = f'@{self.object.author.finger} '
        if self.object.root_parent:
            if self.object.author.finger != self.object.root_parent.author.finger:
                mentions += f'@{self.object.root_parent.author.finger} '
        val.update({'mentions': mentions, 'rendered': self.parent.rendered})
        return(val)
        

class ContentUpdateView(UserOwnsContentMixin, DetailView):
    model = Content
    template_name = "content/vue.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_reply"] = self.is_reply
        context["json_context"] = self.get_json_context()
        return context

    def get_json_context(self):
        context = {
            "currentBrowsingProfileId": getattr(getattr(self.request.user, "profile", None), "id", None),
            "isUserAuthenticated": bool(self.request.user.is_authenticated),
            "isReply": self.is_reply,
            "federate": self.object.federate,
            "includeFollowing": self.object.include_following,
            "pinned": self.object.pinned,
            "showPreview": self.object.show_preview,
            "visibility": self.object.visibility.value
        }

        parent_id = getattr(getattr(self.object, "parent"), "id", None)
        if parent_id is not None:
            context["parent"] = parent_id

        serialized = ContentSerializer(self.object, context={"request": self.request}).data
        context["recipients"] = serialized.get("recipients", [])
        context["text"] = serialized.get("text", "")

        return context

    @property
    def is_reply(self):
        return True if self.object.content_type == ContentType.REPLY else False


# TODO: Implement on front
class ContentDeleteView(UserOwnsContentMixin, DeleteView):
    model = Content
    template_name = "content/delete.html"

    def get_success_url(self):
        next = self.request.GET.get("next")
        if next:
            return next
        return reverse("home")


@method_decorator(activitypub_object_view, name="dispatch")
class ContentView(ContentVisibleForUserMixin, DetailView):
    model = Content
    template_name = "streams/base.html"

    def dispatch(self, request, *args, **kwargs):
        """If share or reply, redirect."""
        self.object = self.get_object()
        if self.object.content_type == ContentType.SHARE:
            return HttpResponseRedirect(self.object.share_of.get_absolute_url())
        elif self.object.content_type == ContentType.REPLY:
            return HttpResponseRedirect(self.object.root_parent.get_absolute_url())
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        uuid = self.kwargs.get("uuid")
        if uuid:
            try:
                return get_object_or_404(Content, uuid=uuid)
            except ValidationError as ex:
                logger.debug("ContentView.get_object - failed at get_object_or_404: %s", ex)
                raise Http404()
        return super().get_object(queryset=queryset)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["json_context"] = self.get_json_context()
        context["meta"] = self.get_page_meta()
        return context

    def get_json_context(self):
        return {
            "currentBrowsingProfileId": getattr(getattr(self.request.user, "profile", None), "id", None),
            "isUserAuthenticated": bool(self.request.user.is_authenticated),
            "streamName": "%s__%s" % (StreamType.CONTENT.value, self.object.channel_group_name),
            "content": self.get_serialized_content(),
        }

    def get_page_meta(self):
        return {
            "type": "article",
            # TODO get longer text depending on user agent, for example twitter
            "title": self.object.short_text,
            "url": self.object.url,
            # TODO this could be for example second paragraph found
            "description": self.object.short_text,
            # TODO get image from text
            "image": get_full_url(static("images/logo/Socialhome-dark-300.png")),
            "author_url": self.object.author.home_url,
            "author_name": self.object.author.name,
        }

    def get_serialized_content(self):
        serializer = ContentSerializer(instance=self.object, context={"request": self.request})
        return serializer.data

socialhome/streams/urls/views.py
from django.conf.urls import url

from socialhome.streams.views import (
    PublicStreamView, TagStreamView, FollowedStreamView, LimitedStreamView, LocalStreamView, TagsStreamView)

app_name = 'streams'

urlpatterns = [
    url(r"^followed/$", FollowedStreamView.as_view(), name="followed"),
    url(r"^limited/$", LimitedStreamView.as_view(), name="limited"),
    url(r"^local/$", LocalStreamView.as_view(), name="local"),
    url(r"^public/$", PublicStreamView.as_view(), name="public"),
    url(r"^tag/uuid-(?P<uuid>[^/]+)/$", TagStreamView.as_view(), name="tag-by-uuid"),
    url(r"^tag/(?P<name>[\w-]+)/$", TagStreamView.as_view(), name="tag"),
    url(r"^tags/$", TagsStreamView.as_view(), name="tags"),
]

socialhome/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{{ request.site.name }}{% endblock title %}</title>
    <meta property="og:site_name" content='{{ request.site.name|addslashes }}' />
    {% block pagetags %}
        <meta property="og:title" content='{{ request.site.name|addslashes }}' />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://{{ request.site.domain }}" />
        <meta property="og:description" content="{% trans "A federated social home." %}" />
        <meta property="og:image" content="https://{{ request.site.domain }}{% static "images/logo/Socialhome-dark-300.png" %}" />
    {% endblock %}
    <meta name="description" content='{% block description %}{% trans "A federated social home." %}{% endblock %}'>
    <meta name="twitter:dnt" content="on">
    <link rel="canonical" href="https://{{ request.site.domain }}{{ request.path }}">

    <link rel="icon" type="image/png" sizes="16x16" href="{% static "images/logo/Socialhome-dark-16.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "images/logo/Socialhome-dark-32.png" %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static "images/logo/Socialhome-dark-96.png" %}">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
        <!-- Compiled project CSS -->
        <link href="{% static "dist/project.css" %}" rel="stylesheet">
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-sm fixed-top bg-dark">
        <div class="container navbar-container">
            <a class="navbar-brand" href="/"><img src="{% static "images/logo/Socialhome-light-24.png" %}" class="mr-2"><span class="align-middle">{{ request.site.name }}</span></a>
            <button type="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#top-navbar" aria-controls="top-navbar" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse mx-auto" id="top-navbar">
                <ul class="navbar-nav mx-auto w-100 justify-content-end text-center">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" id="navbar-streams" href="#">{% trans "Streams" %}</a>
                        <div class="dropdown-menu" aria-labelledby="navbar-streams">
                            {% if request.user.is_authenticated %}
                                <a class="dropdown-item" href="{% url "streams:followed" %}">{% trans "Followed" %}</a>
                                <a class="dropdown-item" href="{% url "users:all-content" username=request.user.username %}">{% trans "My content" %}</a>
                                <a class="dropdown-item" href="{% url "streams:limited" %}">{% trans "Limited" %}</a>
                                <a class="dropdown-item" href="{% url "streams:tags" %}">{% trans "Tags" %}</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url "streams:local" %}">{% trans "Local" %}</a>
                            <a class="dropdown-item" href="{% url "streams:public" %}">{% trans "Public" %}</a>
                        </div>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "content:create" %}">{% trans "Create" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "users:contacts-following" %}">{% trans "Contacts" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "users:detail" request.user.username  %}">{% trans "My Profile" %}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a id="sign-up-link" class="nav-link" href="{% if settings.ACCOUNT_ALLOW_REGISTRATION %}{% url "account_signup" %}{% else %}{{ settings.SOCIALHOME_NODE_LIST_URL }}{% endif %}">
                                {% trans "Sign Up" %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a id="log-in-link" class="nav-link" href="{% url "account_login" %}">{% trans "Log In" %}</a>
                        </li>
                    {% endif %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" id="navbar-menu" href="#">
                            <i class="fa fa-gear" aria-label="{% trans "Menu" %}"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbar-menu">
                            {% if request.user.is_authenticated %}
                                <a class="dropdown-item" href="{% url "dynamic_preferences:user" %}">{% trans "Account" %}</a>
                                <a class="dropdown-item" href="{% url "users:api-token" %}">{% trans "API token" %}</a>
                                <a class="dropdown-item" href="{% url "account_email" %}">{% trans "Emails" %}</a>
                                {% if request.user.is_staff %}
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url "admin:index" %}">{% trans "Admin" %}</a>
                                    <a class="dropdown-item" href="{% url "rq_home" %}">{% trans "Task queue" %}</a>
                                    <div class="dropdown-divider"></div>
                                {% endif %}
                                <a class="dropdown-item" href="{% url "account_logout" %}">{% trans "Logout" %}</a>
                                <div class="dropdown-divider"></div>
                            {% endif %}
                            {% if policy_docs.privacypolicy %}
                                <a class="dropdown-item" href="{% url "privacy-policy" %}">{% trans "Privacy policy" %}</a>
                            {% endif %}
                            {% if policy_docs.tos %}
                                <a class="dropdown-item" href="{% url "terms-of-service" %}">{% trans "Terms of service" %}</a>
                            {% endif %}
                        </div>
                    </li>

                    <form id="search-form" class="form-inline ml-2" method="get" action="{% url "search:global" %}">
                        <div class="input-group input-group-sm">
                            <input class="form-control" type="text" name="q" placeholder="{% trans "Search" %}" value="{{ request.GET.q }}">
                            <span class="input-group-btn">
                                <button class="btn btn-light" type="submit" aria-label="{% trans "Search" %}" title="{% trans "Search" %}"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                </ul>
            </div>
        </div>
    </nav>

    <div class="main-container {% block containertype %}container{% endblock %}">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
        <!-- JavaScript locales -->
        <script type="text/javascript" src="{% url "javascript-catalog" %}"></script>
        <!-- Compiled project JS -->
        <script src="{% static "dist/project.js" %}"></script>
    {% endblock javascript %}
</body>
</html>